# -*- coding: utf-8 -*-
"""批量填充 socialfi.i18n.js 的 en 翻译（只替换 en 块中的空值）"""
import re, io, sys, os

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

TRANS = {
 'sfx.k1': 'Nova SocialFi · On-chain Ecosystem',
 'sfx.k2': '🌠 On-chain Ecosystem Universe',
 'sfx.k3': 'All ten SocialFi modes run on Nova: fan tokens, revenue shares, achievement badges, prediction markets, verifiable blind boxes, content curation, social graph & recommendations, reputation system, creator bonds and fractional NFTs. Content auto-pins to the chain storage network, and the recommendation engine can be published as a compute task in one click.',
 'sfx.k4': '👤 My On-chain Reputation',
 'sfx.k5': 'Shows real-time reputation (0-100), entitlements and personalized recommendations after connecting a wallet.',
 'sfx.k6': '🪙 Fan Tokens',
 'sfx.k7': '🤝 Revenue Shares',
 'sfx.k8': '🏅 Achievements',
 'sfx.k9': '📊 Prediction Markets',
 'sfx.k10': '🎁 Blind Boxes',
 'sfx.k11': '📚 Curation',
 'sfx.k12': '🕸️ Social Graph',
 'sfx.k13': '⭐ Reputation Details',
 'sfx.k14': '🏦 Creator Bonds',
 'sfx.k15': '🧩 Fractional NFTs',
 'sfx.k16': 'Issue Fan Token',
 'sfx.k17': 'Symbol (uppercase letters/digits, ≤10)',
 'sfx.k18': 'Token Name',
 'sfx.k19': 'Total Supply',
 'sfx.k20': 'Initial Price (NOVA)',
 'sfx.k21': 'Avatar CID (optional, auto-pinned on-chain)',
 'sfx.k22': '🚀 Issue in One Click',
 'sfx.k23': 'Fan Token Market',
 'sfx.k24': 'Fixed low fees support high-frequency trading; bonding curves let early buyers gain as sales grow; holding tokens unlocks voting power.',
 'sfx.k25': 'Loading…',
 'sfx.k26': 'Open Revenue Share',
 'sfx.k27': 'Project Name',
 'sfx.k28': 'Description',
 'sfx.k29': '🤝 Open Project',
 'sfx.k30': 'Invest in "people you like"',
 'sfx.k31': 'Loading…',
 'sfx.k32': 'Issue Achievement Badge',
 'sfx.k33': 'Achievement Title',
 'sfx.k34': 'Description',
 'sfx.k35': 'Badge Art',
 'sfx.k36': '🏅 Create Achievement',
 'sfx.k37': 'Award to address (0x + 40-char hex)',
 'sfx.k38': 'Achievement ID',
 'sfx.k39': '🎖️ Award (soulbound)',
 'sfx.k40': 'Achievement Gallery (non-transferable)',
 'sfx.k41': 'Loading…',
 'sfx.k42': 'Open Prediction Market',
 'sfx.k43': 'Question',
 'sfx.k44': 'Options (comma-separated)',
 'sfx.k45': 'Close time (hours)',
 'sfx.k46': 'Oracle address (default self)',
 'sfx.k47': '📊 Open Market',
 'sfx.k48': 'Express opinions with your wallet',
 'sfx.k49': 'Loading…',
 'sfx.k50': 'List Blind Box (commit-reveal verifiable randomness)',
 'sfx.k51': 'Blind Box Name',
 'sfx.k52': 'Unit Price (NOVA)',
 'sfx.k53': 'Tier JSON (name/weight/reward_type/reward_amount or reward_cid)',
 'sfx.k54': '🎁 List Blind Box',
 'sfx.k55': 'Open to verify randomness',
 'sfx.k56': 'Loading…',
 'sfx.k57': 'Create Curation NFT (taste as asset)',
 'sfx.k58': 'Playlist / Watchlist Title',
 'sfx.k59': 'Items (one per line, or CID)',
 'sfx.k60': 'Price (NOVA)',
 'sfx.k61': 'Cover CID (optional)',
 'sfx.k62': '📚 Create Curation',
 'sfx.k63': 'Collect and split revenue (curator gets 90%)',
 'sfx.k64': 'Loading…',
 'sfx.k65': 'Post a Moment (can carry CID to on-chain storage)',
 'sfx.k66': 'Content',
 'sfx.k67': 'Content CID (optional, auto-pinned on-chain)',
 'sfx.k68': '🚀 Post',
 'sfx.k69': 'Follow address',
 'sfx.k70': '➕ Follow',
 'sfx.k71': 'Feed',
 'sfx.k72': 'Loading…',
 'sfx.k73': '🌟 My Recommendations (on-chain compute engine)',
 'sfx.k74': 'Loading…',
 'sfx.k75': '⚡ Publish Recommendation as Compute Task',
 'sfx.k76': '🗄️ Storage Network',
 'sfx.k77': '⚡ Compute Market',
 'sfx.k78': 'Recommendation results can be published as on-chain compute tasks; see the compute page for the task market.',
 'sfx.k79': '⭐ Reputation Details (0-100)',
 'sfx.k80': 'Computed in real time from staking, check-ins, contract deploys, recommendations, achievements, curation, fan tokens and content interaction; high scores (≥80) get a 50% trading fee discount and priority in presales and airdrops.',
 'sfx.k81': 'Loading…',
 'sfx.k82': 'Issue Creator Bond (royalty-backed)',
 'sfx.k83': 'Bond Name',
 'sfx.k84': 'Funding Goal (NOVA)',
 'sfx.k85': 'Annual Rate (0-50%)',
 'sfx.k86': 'Term (days)',
 'sfx.k87': '🏦 Issue Bond',
 'sfx.k88': 'Bond Market',
 'sfx.k89': 'Loading…',
 'sfx.k90': 'Fractionalize NFT (shared ownership)',
 'sfx.k91': 'Asset Name',
 'sfx.k92': 'Source (NFT ID or CID)',
 'sfx.k93': 'Total Fractions',
 'sfx.k94': 'Price per Share (NOVA)',
 'sfx.k95': '🧩 Fractionalize',
 'sfx.k96': 'Fractions Market',
 'sfx.k97': 'Loading…',
 'sfx.k98': '📜 On-chain Activity (recent events)',
 'sfx.k99': 'Loading…',
}

path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'socialfi.i18n.js')
with open(path, 'r', encoding='utf-8') as f:
    c = f.read()
en_start = c.find('  en: {')
head, en = c[:en_start], c[en_start:]
def rep(m):
    key = m.group(1)
    val = TRANS.get(key, '')
    return "'%s': '%s'" % (key, val.replace("'", "\\'"))
en2, n = re.subn(r"'((?:sfx)\.k\d+)': ''", rep, en)
with open(path, 'w', encoding='utf-8') as f:
    f.write(head + en2)
print('已填充 %d 条（en 块剩余空值: %d）' % (len(TRANS), en2.count("': ''")))
